# Assignment

Q1. Write the NumPy program to create a 2d array with 6 on the border
and 0 inside?

    Expected OutputOriginal array-
    [ [6 6 6 6 6]
     [ 6 6 6 6 6]
     [ 6 6 6 6 6 ]
    [ 6 6 6 6 6 ]
    [ 6 6 6 6 ] ].
    6 on the border and 0 inside in the array-
    [[ 6 6 6 6 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 0 0 0 6]
    [ 6 6 6 6 6]].

In [64]:
import numpy as np

def zero_in(arr):
    print('Input array:')    
    print(arr)
    arr[1:-1,1:-1] = 0
    print('\n')
    print('Result')    
    print(arr)

In [65]:
zero_in(np.full((5, 5), 6))

Input array:
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


Result
[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


Q2. Write the NumPy program to create a 8x8 matrix and fill it with the
checkerboard pattern?
    
    Checkerboard pattern-
    [[3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]
    [3 9 3 9 3 9 3 9]
    [9 3 9 3 9 3 9 3]].

In [66]:
import numpy as np
def checkboard(arr):    
    print("Checkerboard pattern:")    
    arr[1::2,::2] = 9
    arr[::2,1::2] = 9
    print(arr)

In [67]:
checkboard(np.full((8,8), 3, dtype=int))

Checkerboard pattern:
[[3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]]


Q3. Write the NumPy program to create an empty and a full array.
 
     Expected Output-
    [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306]
    [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308]
    [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]]
    [[6 6 6]
    [6 6 6]
    [6 6 6]]


In [68]:
import numpy as np

# Creating Empty array
empty = np.empty((3,4), dtype=float)
print('Empty array:')
print(empty)
print('\n')
# Creating full array
full = np.full((3,3), 6)
print('Full array:')
print(full)

Empty array:
[[3.55010435e-316 0.00000000e+000 4.27366784e-321 2.46463699e-316]
 [6.91316113e-310 6.91316113e-310 6.91316113e-310 6.91316113e-310]
 [3.55010435e-316 9.88131292e-324 1.90979621e-313 0.00000000e+000]]


Full array:
[[6 6 6]
 [6 6 6]
 [6 6 6]]


Q4. Write the NumPy program to convert the values of Centigrade
degrees into the Fahrenheit degrees and the centigrade values are
stored in the NumPy array.
    
    Sample Array -[0, 12, 45.21 ,34, 99.91]
    Expected OutputValues in Fahrenheit degrees-
    [ 0. 12. 45.21 34. 99.91]
    Values in Centigrade degrees-
    [-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [69]:
import numpy as np

def to_fahrenheit(arr):
  arr = np.array(arr)
  print("Values in Fahrenheit:")
  print(arr)
  print('\n')
  print("Values in  Centigrade degrees:")
  print((5*(arr-32))/9)

In [70]:
to_fahrenheit([0, 12, 45.21 ,34, 99.91])

Values in Fahrenheit:
[ 0.   12.   45.21 34.   99.91]


Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


Q5. Write the NumPy program to find the real and imaginary parts of an
array of complex numbers?

    Expected OutputOriginal array [ 1.00000000+0.j 0.70710678+0.70710678j]
    Real part of the array-
    [ 1. 0.70710678]
    Imaginary part of the array-
    [ 0. 0.70710678]

In [71]:
import numpy as np

def complex_nums(arr):
  arr = np.array(arr)
  print('Real part of the array-')
  print(arr.real)
  print('\n')
  print('Imaginary part of the array-')
  print(arr.imag)

In [72]:
complex_nums([ 1.00000000+0.j, 0.70710678+0.70710678j])

Real part of the array-
[1.         0.70710678]


Imaginary part of the array-
[0.         0.70710678]


Q6. Write the NumPy program to test whether each element of a 1-D
array is also present in the second array?

    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [0, 40]
    Compare each element of array1 and array2
    [ True False False True False]


In [73]:
import numpy as np

def check_arrays(arr1, arr2):
  print('Array1:')
  arr1 = np.array(arr1)
  print(arr1)
  print('Array2:')
  arr2 = np.array(arr2)
  print(arr2)
  print('Comparing each element of array1 and array2')
  print(np.in1d(arr1, arr2))

In [74]:
arr1 = [0,10,20,40,60]
arr2 = [0,40]
check_arrays(arr1, arr2)

Array1:
[ 0 10 20 40 60]
Array2:
[ 0 40]
Comparing each element of array1 and array2
[ True False False  True False]


Q7. Write the NumPy program to find common values between two
arrays?
    
    Expected OutputArray1: [ 0 10 20 40 60]
    Array2: [10, 30, 40]
    Common values between two arrays-
    [10 40]

In [75]:
import numpy as np

def common_values(arr1, arr2):
  print('Array1:')
  arr1 = np.array(arr1)
  print(arr1)
  print('Array2:')
  arr2 = np.array(arr2)
  print(arr2)
  print('Common values between two arrays-') 
  print(np.intersect1d(arr1, arr2)) 

In [76]:
common_values([0, 10, 20, 40, 60], [10, 30, 40])

Array1:
[ 0 10 20 40 60]
Array2:
[10 30 40]
Common values between two arrays-
[10 40]


Q8. Write the NumPy program to get the unique elements of an array?

    Expected OutputOriginal array-
    [10 10 20 20 30 30]
    Unique elements of the above array-
    [10 20 30]
    P a g e 14 | 44
    Original array-
    [[1 1]
    [2 3]]
    Unique elements of the above array-
    [1 2 3]

In [77]:
import numpy as np

def unique(arr):
  arr = np.array(arr)
  print('Original Array-')
  print(arr)
  print('Unique elements of the above array-')
  print(np.unique(arr))

In [78]:
unique([10, 10, 20, 20, 30, 30])

Original Array-
[10 10 20 20 30 30]
Unique elements of the above array-
[10 20 30]


In [79]:
unique([[1, 1],[2, 3]])

Original Array-
[[1 1]
 [2 3]]
Unique elements of the above array-
[1 2 3]


Q9. Write the NumPy program to find the set exclusive-or of two arrays.
Set exclusive-or will return the sorted, unique values that are in
only one (not both) of the input arrays?

    Array1- [ 0 10 20 40 60 80]
    Array2- [10, 30, 40, 50, 70]
    Unique values that are in only one (not both) of the input arrays-
    [ 0 20 30 50 60 70 80]

In [80]:
import numpy as np

def exc_or(arr1, arr2):
  print('Array1:')
  arr1 = np.array(arr1)
  print(arr1)
  print('Array2:')
  arr2 = np.array(arr2)
  print(arr2)  
  print('Unique values that are in only one (not both) of the input arrays-')
  print(np.setxor1d(arr1, arr2))

In [81]:
exc_or([0, 10, 20, 40, 60, 80],[10, 30, 40, 50, 70])

Array1:
[ 0 10 20 40 60 80]
Array2:
[10 30 40 50 70]
Unique values that are in only one (not both) of the input arrays-
[ 0 20 30 50 60 70 80]


Q10. Write the NumPy program to test if all elements in an array
evaluate to True ?
 
Note: 0 evaluates to False in NumPy

In [82]:
import numpy as np

def eval_true(arr):
  print(np.all(arr))

In [83]:
eval_true([10, 50, 0, 20, 0])
eval_true([10,52,41])

False
True


Q11. Write the NumPy program to test whether any array element along
the given axis evaluates to True?
 
Note: 0 evaluates to False in NumPy

In [84]:
import numpy as np

def any_true(arr):
  return np.any(arr)

In [85]:
print(any_true([10,20,0,22]))
print(any_true([0,0]))

True
False


Q12. Write the NumPy program to construct an array by repeating?

    Sample array- [1, 2, 3, 4]
    Expected OutputOriginal array
    [1, 2, 3, 4]
    Repeating 2 times
    [1 2 3 4 1 2 3 4]
    Repeating 3 times
    [1 2 3 4 1 2 3 4 1 2 3 4]

In [86]:
import numpy as np

def repeat_array(arr, multiplier):
  arr = np.array(arr)
  print('Original array')
  print(arr)
  print('\n')
  print(f'Repeating {multiplier} times:')
  print(np.repeat(arr, multiplier))

In [87]:
repeat_array([1, 2, 3, 4], 2)

Original array
[1 2 3 4]


Repeating 2 times:
[1 1 2 2 3 3 4 4]


In [89]:
repeat_array(3, 5)

Original array
3


Repeating 5 times:
[3 3 3 3 3]


Q13. Write the NumPy program to find the indices of the maximum and
minimum values with the given axis of an array?

    Original array- [1 2 3 4 5 6]
    Maximum Values- 5
    Minimum Values- 0

In [90]:
def min_max(arr):
  arr = np.array(arr)
  print(f'Original array- {arr}')
  print(f'Maximum Value- {np.argmax(arr)}')
  print(f'Minimum Value- {np.argmin(arr)}')

In [91]:
min_max([1,2,3,4,5,6])

Original array- [1 2 3 4 5 6]
Maximum Value- 5
Minimum Value- 0


Q14. Write the NumPy program compare two arrays using numpy?

    Array a- [1 2]
    Array b- [4 5]
    a > b
    [False False]
    a >= b
    [False False]
    a < b
    [ True True]
    a <= b
    [ True True]


In [92]:
a = np.array([1, 2])
b = np.array([4, 5])
print("Array a- ",a)
print("Array b- ",b)
print("a > b")
print(np.greater(a, b))
print("a >= b")
print(np.greater_equal(a, b))
print("a < b")
print(np.less(a, b))
print("a <= b")
print(np.less_equal(a, b))

Array a-  [1 2]
Array b-  [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


Q15. Write the NumPy program to sort an along the first, last axis of an
array?

    Sample array- [[2,5],[4,4]]
    Expected OutputOriginal array:
    [[4 6]
    [2 1]]
    Sort along the first axis:
    [[2 1]
    [4 6]]
    Sort along the last axis-
    [[1 2]
    [4 6]]

In [93]:
import numpy as np

a = np.array([[4, 6],[2, 1]])
print("Original array: ")
print(a)
print("Sort along the first axis: ")
x = np.sort(a, axis=0)
print(x)
print("Sort along the last axis: ")
y = np.sort(x, axis=1)
print(y)

Original array: 
[[4 6]
 [2 1]]
Sort along the first axis: 
[[2 1]
 [4 6]]
Sort along the last axis: 
[[1 2]
 [4 6]]


Q16. Write the NumPy program to sort pairs of first name and last name
return their indices (first by last name, then by first name).

    first_names - ( Betsey, Shelley, Lanell, Genesis, Margery )
    last_names - ( Battle, Brien, Plotner, Stahl, Woolum )
    Expected Output-
    [1 3 2 4 0]

In [94]:
first_names =    ('Margery', 'Betsey', 'Shelley', 'Lanell', 'Genesis')
last_names = ('Woolum', 'Battle', 'Plotner', 'Brien', 'Stahl')
x = np.lexsort((first_names, last_names))
print(x)

[1 3 2 4 0]


Q17. Write the NumPy program to get the values and indices of the
elements that are bigger than 10 in the given array?

    Original array-
    [[ 0 10 20]
    [20 30 40]]
    Values bigger than 10 = [20 20 30 40]
    Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))

In [95]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))

Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


Q18. Write the NumPy program to find the memory size of a NumPy
array?

    Expected Output128 bytes


In [96]:
n = np.zeros((4,4))
print(f'{n.size * n.itemsize} bytes')

128 bytes


## Great Job!